package com.voxline.voice.client.gui;

import com.voxline.voice.client.ClientVoiceController;
import com.voxline.voice.network.GroupActionC2SPacket;
import com.voxline.voice.network.GroupStateS2CPacket;
import com.voxline.voice.network.VoiceNetwork;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.util.List;

public final class GroupScreen extends Screen {
    private static final int VW=1000,VH=570;private final Screen parent;private float scale,ox,oy;private double mx,my;private int candidateOffset;
    public GroupScreen(Screen parent){super(Component.literal("Voxline Groups"));this.parent=parent;}@Override public boolean isPauseScreen(){return false;}
    @Override public void render(GuiGraphics g,int mouseX,int mouseY,float pt){renderBackground(g);transform(mouseX,mouseY);UiTheme t=UiTheme.current();g.pose().pushPose();g.pose().translate(ox,oy,0);g.pose().scale(scale,scale,1);UiKit.panel(g,18,18,964,534,0xF20F1316,t.border());UiKit.panel(g,310,6,380,66,t.panel(),t.border());UiKit.centered(g,"GROUP VOICE",500,25,t.text());UiKit.centered(g,"DISTANCE-INDEPENDENT PRIVATE CHANNEL",500,45,t.muted());
        GroupStateS2CPacket s=ClientVoiceController.get().groupState();UiKit.text(g,"GROUP STATUS",42,95,t.accent());UiKit.panel(g,40,112,920,74,t.panel(),t.border());if(!ClientVoiceController.get().policy().groupsEnabled()){UiKit.text(g,"Groups are disabled by this server.",60,140,t.red());}else if(!s.inGroup()){UiKit.text(g,"You are not in a group.",60,132,t.text());UiKit.text(g,"Create one, then invite online players. Group voice ignores distance and dimension.",60,151,t.muted());UiKit.button(g,new UiKit.Rect(750,130,180,34),"CREATE GROUP",true,new UiKit.Rect(750,130,180,34).hit(mx,my),t);}else{UiKit.text(g,s.groupName(),60,130,t.text());UiKit.text(g,"G = Group PTT   •   V = Proximity PTT   •   V+G = Both",60,151,t.muted());UiKit.text(g,s.members().size()+" / "+ClientVoiceController.get().policy().maxGroupSize()+" MEMBERS",745,140,t.purple());}
        if(s.hasInvite()){UiKit.panel(g,40,196,920,52,0xF2241E2B,t.purple());UiKit.text(g,UiKit.fit(s.inviteLabel(),650),58,216,t.text());UiKit.button(g,new UiKit.Rect(735,207,96,30),"ACCEPT",true,new UiKit.Rect(735,207,96,30).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(840,207,96,30),"DECLINE",false,new UiKit.Rect(840,207,96,30).hit(mx,my),t);}
        int top=s.hasInvite()?265:205;UiKit.text(g,s.inGroup()?"MEMBERS":"ONLINE PLAYERS",42,top,t.accent());if(s.inGroup())drawMembers(g,t,s,top+18);else drawCandidates(g,t,s,top+18,8,false);if(s.inGroup()){UiKit.text(g,"INVITE PLAYERS",540,top,t.accent());drawCandidates(g,t,s,top+18,5,true);}
        UiKit.button(g,new UiKit.Rect(40,510,150,30),"BACK",false,new UiKit.Rect(40,510,150,30).hit(mx,my),t);if(s.inGroup()){boolean leader=isLeader(s);UiKit.button(g,new UiKit.Rect(610,510,150,30),leader?"DISBAND":"LEAVE",false,new UiKit.Rect(610,510,150,30).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(775,510,185,30),"OPEN PLAYER MIXER",true,new UiKit.Rect(775,510,185,30).hit(mx,my),t);}g.pose().popPose();}
    private void drawMembers(GuiGraphics g,UiTheme t,GroupStateS2CPacket s,int y){int max=7;for(int i=0;i<Math.min(max,s.members().size());i++){GroupStateS2CPacket.Member m=s.members().get(i);int ry=y+i*39;UiKit.panel(g,40,ry,470,34,t.panel2(),m.leader()?t.purple():t.border());AvatarRenderer.draw(g,m.id(),48,ry+5,24);UiKit.text(g,UiKit.fit(m.name(),170),80,ry+8,m.online()?t.text():t.muted());UiKit.text(g,m.leader()?"LEADER":m.online()?"ONLINE":"OFFLINE",258,ry+8,m.leader()?t.purple():m.online()?t.green():t.muted());if(isLeader(s)&&!m.leader()){UiKit.button(g,new UiKit.Rect(335,ry+4,76,26),"PROMOTE",false,new UiKit.Rect(335,ry+4,76,26).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(417,ry+4,82,26),"KICK",false,new UiKit.Rect(417,ry+4,82,26).hit(mx,my),t);}}}
    private void drawCandidates(GuiGraphics g,UiTheme t,GroupStateS2CPacket s,int y,int max,boolean inviteButtons){List<GroupStateS2CPacket.Candidate> c=s.candidates();int start=Math.max(0,Math.min(candidateOffset,Math.max(0,c.size()-max)));int x=inviteButtons?540:40,w=inviteButtons?420:920;for(int j=0;j<Math.min(max,c.size()-start);j++){int i=start+j,ry=y+j*39;GroupStateS2CPacket.Candidate p=c.get(i);UiKit.panel(g,x,ry,w,34,t.panel2(),t.border());AvatarRenderer.draw(g,p.id(),x+8,ry+5,24);UiKit.text(g,UiKit.fit(p.name(),inviteButtons?210:600),x+40,ry+8,t.text());if(inviteButtons)UiKit.button(g,new UiKit.Rect(x+w-100,ry+4,90,26),"INVITE",false,new UiKit.Rect(x+w-100,ry+4,90,26).hit(mx,my),t);}}
    @Override public boolean mouseClicked(double x,double y,int b){transform(x,y);if(b!=0)return super.mouseClicked(x,y,b);GroupStateS2CPacket s=ClientVoiceController.get().groupState();if(new UiKit.Rect(40,510,150,30).hit(mx,my)){onClose();return true;}if(!s.inGroup()&&new UiKit.Rect(750,130,180,34).hit(mx,my)){send(GroupActionC2SPacket.Action.CREATE,null);return true;}if(s.hasInvite()){if(new UiKit.Rect(735,207,96,30).hit(mx,my)){send(GroupActionC2SPacket.Action.ACCEPT,null);return true;}if(new UiKit.Rect(840,207,96,30).hit(mx,my)){send(GroupActionC2SPacket.Action.DECLINE,null);return true;}}
        int top=s.hasInvite()?283:223;if(s.inGroup()&&isLeader(s)){for(int i=0;i<Math.min(7,s.members().size());i++){var m=s.members().get(i);int ry=top+i*39;if(!m.leader()&&new UiKit.Rect(335,ry+4,76,26).hit(mx,my)){send(GroupActionC2SPacket.Action.PROMOTE,m.id());return true;}if(!m.leader()&&new UiKit.Rect(417,ry+4,82,26).hit(mx,my)){send(GroupActionC2SPacket.Action.KICK,m.id());return true;}}int start=Math.max(0,Math.min(candidateOffset,Math.max(0,s.candidates().size()-5)));for(int j=0;j<Math.min(5,s.candidates().size()-start);j++){int ry=top+j*39;if(new UiKit.Rect(860,ry+4,90,26).hit(mx,my)){send(GroupActionC2SPacket.Action.INVITE,s.candidates().get(start+j).id());return true;}}}
        if(s.inGroup()&&new UiKit.Rect(610,510,150,30).hit(mx,my)){send(isLeader(s)?GroupActionC2SPacket.Action.DISBAND:GroupActionC2SPacket.Action.LEAVE,null);return true;}if(s.inGroup()&&new UiKit.Rect(775,510,185,30).hit(mx,my)){Minecraft.getInstance().setScreen(new PlayerMixerScreen(this));return true;}return true;}
    @Override public boolean mouseScrolled(double x,double y,double delta){candidateOffset=Math.max(0,candidateOffset+(delta<0?1:-1));return true;}private boolean isLeader(GroupStateS2CPacket s){return Minecraft.getInstance().player!=null&&s.inGroup()&&s.leader().equals(Minecraft.getInstance().player.getUUID());}private static void send(GroupActionC2SPacket.Action a,java.util.UUID id){VoiceNetwork.sendGroupAction(new GroupActionC2SPacket(a,id));}
    @Override public void onClose(){Minecraft.getInstance().setScreen(parent);}private void transform(double x,double y){scale=Math.max(.25f,Math.min((width-8f)/VW,(height-8f)/VH));ox=(width-VW*scale)/2;oy=(height-VH*scale)/2;mx=(x-ox)/scale;my=(y-oy)/scale;}
}
