package com.voxline.voice.client.gui;

import com.voxline.voice.client.ClientVoiceController;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.util.List;
import java.util.UUID;

public final class PlayerMixerScreen extends Screen {
    private static final int VW=900,VH=520,ROWS=7;private final Screen parent;private float scale,ox,oy;private double mx,my;private int page;private UUID dragging;
    public PlayerMixerScreen(Screen parent){super(Component.literal("Player Voice Mixer"));this.parent=parent;}@Override public boolean isPauseScreen(){return false;}
    @Override public void render(GuiGraphics g,int mouseX,int mouseY,float pt){renderBackground(g);transform(mouseX,mouseY);UiTheme t=UiTheme.current();g.pose().pushPose();g.pose().translate(ox,oy,0);g.pose().scale(scale,scale,1);UiKit.panel(g,15,15,870,490,0xF20F1316,t.border());UiKit.panel(g,270,5,360,62,t.panel(),t.border());UiKit.centered(g,"PLAYER VOICE MIXER",450,23,t.text());UiKit.centered(g,"LOCAL SESSION • 0–200% PER PLAYER",450,43,t.muted());List<ClientVoiceController.KnownPlayer> list=ClientVoiceController.get().knownPlayers();int pages=Math.max(1,(list.size()+ROWS-1)/ROWS);page=Math.min(page,pages-1);int start=page*ROWS;UiKit.text(g,"ONLINE + GROUP + RECENT",45,92,t.accent());UiKit.text(g,"Group members remain mixable even when they are far away or in another dimension.",45,108,t.muted());if(list.isEmpty()){UiKit.panel(g,45,135,810,95,t.panel(),t.border());UiKit.centered(g,"No other players are available yet.",450,170,t.muted());}for(int j=0;j<Math.min(ROWS,list.size()-start);j++){int i=start+j,y=135+j*47;var p=list.get(i);var mix=ClientVoiceController.get().mix(p.id());UiKit.panel(g,45,y,810,40,t.panel2(),p.groupMember()?t.purple():t.border());AvatarRenderer.draw(g,p.id(),53,y+5,30);UiKit.text(g,UiKit.fit(p.name(),185),92,y+7,mix.muted()?t.muted():t.text());UiKit.text(g,p.groupMember()?"GROUP":p.distance()>=0?String.format("%.0fm",p.distance()):"REMOTE",275,y+7,p.groupMember()?t.purple():t.accent());UiKit.slider(g,new UiKit.Rect(385,y+12,245,14),mix.volume()/2f,t.accent(),t);UiKit.text(g,Math.round(mix.volume()*100)+"%",645,y+7,t.text());UiKit.button(g,new UiKit.Rect(730,y+5,105,28),mix.muted()?"UNMUTE":"MUTE",mix.muted(),new UiKit.Rect(730,y+5,105,28).hit(mx,my),t);}
        UiKit.button(g,new UiKit.Rect(45,460,130,28),"BACK",false,new UiKit.Rect(45,460,130,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(190,460,170,28),"RESET ALL MIX",false,new UiKit.Rect(190,460,170,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(590,460,100,28),"< PREV",false,new UiKit.Rect(590,460,100,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(700,460,100,28),"NEXT >",false,new UiKit.Rect(700,460,100,28).hit(mx,my),t);UiKit.centered(g,(page+1)+" / "+pages,835,469,t.muted());g.pose().popPose();}
    @Override public boolean mouseClicked(double x,double y,int b){transform(x,y);if(b!=0)return super.mouseClicked(x,y,b);if(new UiKit.Rect(45,460,130,28).hit(mx,my)){onClose();return true;}if(new UiKit.Rect(190,460,170,28).hit(mx,my)){ClientVoiceController.get().resetMix();return true;}if(new UiKit.Rect(590,460,100,28).hit(mx,my)){page=Math.max(0,page-1);return true;}if(new UiKit.Rect(700,460,100,28).hit(mx,my)){page++;return true;}List<ClientVoiceController.KnownPlayer> list=ClientVoiceController.get().knownPlayers();int start=page*ROWS;for(int j=0;j<Math.min(ROWS,list.size()-start);j++){var p=list.get(start+j);int ry=135+j*47;if(new UiKit.Rect(385,ry+8,245,22).hit(mx,my)){dragging=p.id();updateVolume(p.id());return true;}if(new UiKit.Rect(730,ry+5,105,28).hit(mx,my)){ClientVoiceController.get().togglePlayerMute(p.id());return true;}}return true;}
    @Override public boolean mouseDragged(double x,double y,int b,double dx,double dy){transform(x,y);if(b==0&&dragging!=null){updateVolume(dragging);return true;}return super.mouseDragged(x,y,b,dx,dy);}@Override public boolean mouseReleased(double x,double y,int b){dragging=null;return super.mouseReleased(x,y,b);}private void updateVolume(UUID id){float v=(float)((mx-385)/245.0);ClientVoiceController.get().setPlayerVolume(id,Math.max(0,Math.min(1,v))*2f);}@Override public void onClose(){Minecraft.getInstance().setScreen(parent);}private void transform(double x,double y){scale=Math.max(.25f,Math.min((width-8f)/VW,(height-8f)/VH));ox=(width-VW*scale)/2;oy=(height-VH*scale)/2;mx=(x-ox)/scale;my=(y-oy)/scale;}
}
