package com.voxline.voice.client.gui;

import com.voxline.voice.VoxlineVoice;
import com.voxline.voice.audio.AudioDevices;
import com.voxline.voice.client.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.UUID;

public final class VoiceSettingsScreen extends Screen {
    private static final int VW=1000,VH=570;private static final String[] TABS={"GENERAL","AUDIO","OVERLAY","GROUPS","KEYBINDS","THEMES","ADVANCED"};private final Screen parent;private float scale,ox,oy;private double mx,my;private int page;private int drag=-1;
    public VoiceSettingsScreen(Screen parent){super(Component.literal("Voxline Voice Settings"));this.parent=parent;}@Override public boolean isPauseScreen(){return false;}
    @Override public void render(GuiGraphics g,int mouseX,int mouseY,float pt){renderBackground(g);transform(mouseX,mouseY);UiTheme t=UiTheme.current();g.pose().pushPose();g.pose().translate(ox,oy,0);g.pose().scale(scale,scale,1);UiKit.panel(g,12,18,976,532,0xF20F1316,t.border());UiKit.panel(g,320,3,360,68,t.panel(),t.border());UiKit.centered(g,"VOICE MOD SETTINGS",500,22,t.text());UiKit.centered(g,"VOXLINE STUDIO • v"+VoxlineVoice.VERSION,500,44,t.muted());for(int i=0;i<TABS.length;i++){int x=28+i*136;UiKit.button(g,new UiKit.Rect(x,84,128,34),TABS[i],i==page,new UiKit.Rect(x,84,128,34).hit(mx,my),t);}switch(page){case 1->audio(g,t);case 4->keybinds(g,t);case 5->themes(g,t);case 6->advanced(g,t);default->general(g,t);}bottom(g,t);g.pose().popPose();}
    private void general(GuiGraphics g,UiTheme t){ClientConfig c=ClientConfig.INSTANCE;UiKit.text(g,"VOICE SETTINGS",30,135,t.accent());int x=30,y=152,w=620;setting(g,t,x,y,w,"Master Voice Volume","Overall incoming voice volume");UiKit.slider(g,new UiKit.Rect(345,y+15,210,14),c.masterVolume/2f,t.accent(),t);value(g,t,565,y+9,70,26,Math.round(c.masterVolume*100)+"%");y+=48;setting(g,t,x,y,w,"Group Volume","Extra mix level for distance-independent group voice");UiKit.slider(g,new UiKit.Rect(345,y+15,210,14),c.groupVolume/2f,t.purple(),t);value(g,t,565,y+9,70,26,Math.round(c.groupVolume*100)+"%");y+=48;setting(g,t,x,y,w,"Activation Mode","Push-to-Talk or comfortable hysteresis Voice Activation");value(g,t,405,y+9,230,26,c.activationMode==ClientConfig.ActivationMode.PUSH_TO_TALK?"Push-to-Talk":"Voice Activation");y+=48;setting(g,t,x,y,w,"Noise Processing","Adaptive noise floor + smooth expander");UiKit.toggle(g,new UiKit.Rect(570,y+10,65,26),c.suppressionStrength>.05f,t);y+=48;setting(g,t,x,y,w,"3D Spatial Voice","Equal-power stereo positioning for proximity voice");UiKit.toggle(g,new UiKit.Rect(570,y+10,65,26),c.spatialVoice,t);y+=48;setting(g,t,x,y,w,"Proximity Range","Personal hearing cap; server policy always wins");UiKit.slider(g,new UiKit.Rect(345,y+15,210,14),(c.proximityRange-4)/60f,t.accent(),t);value(g,t,565,y+9,70,26,Math.round(Math.min(c.proximityRange,ClientVoiceController.get().policy().maxRange()))+" m");y+=48;setting(g,t,x,y,w,"Microphone Device","Click to cycle available inputs");value(g,t,330,y+9,305,26,UiKit.fit(c.inputDevice,270));y+=48;setting(g,t,x,y,w,"Speaker Device","Click to cycle available outputs");value(g,t,330,y+9,305,26,UiKit.fit(c.outputDevice,270));
        UiKit.text(g,"LIVE PREVIEW",680,135,t.accent());UiKit.panel(g,675,152,285,142,t.panel(),t.border());UUID id=Minecraft.getInstance().player!=null?Minecraft.getInstance().player.getUUID():UUID.nameUUIDFromBytes("voxline-preview".getBytes(StandardCharsets.UTF_8));String name=Minecraft.getInstance().player!=null?Minecraft.getInstance().player.getName().getString():"harekuto";AvatarRenderer.draw(g,id,692,174,34,c.showHatLayer,1f);UiKit.text(g,name,738,177,t.text());UiKit.text(g,ClientVoiceController.get().groupState().inGroup()?"GROUP READY":"PROXIMITY",738,195,ClientVoiceController.get().groupState().inGroup()?t.purple():t.green());for(int i=0;i<8;i++){int bh=5+(i*5%18);g.fill(695+i*9,260-bh,701+i*9,260,i<6?t.green():t.purple());}UiKit.text(g,"V = NEAR",805,238,t.accent());UiKit.text(g,"G = GROUP",805,254,t.purple());
        UiKit.text(g,"SERVER / GROUP",680,315,t.accent());UiKit.panel(g,675,332,285,166,t.panel(),t.border());var p=ClientVoiceController.get().policy();var s=ClientVoiceController.get().groupState();line(g,t,692,352,"Voice",p.voiceEnabled()?"READY":"DISABLED",p.voiceEnabled()?t.green():t.red());line(g,t,692,378,"Groups",p.groupsEnabled()?"ENABLED":"DISABLED",p.groupsEnabled()?t.purple():t.red());line(g,t,692,404,"Server Range",Math.round(p.maxRange())+" m",t.accent());line(g,t,692,430,"Group",s.inGroup()?UiKit.fit(s.groupName(),120):"NONE",s.inGroup()?t.purple():t.muted());UiKit.button(g,new UiKit.Rect(692,458,118,28),"GROUPS",s.inGroup(),new UiKit.Rect(692,458,118,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(820,458,118,28),"MIXER",false,new UiKit.Rect(820,458,118,28).hit(mx,my),t);}
    private void audio(GuiGraphics g,UiTheme t){ClientConfig c=ClientConfig.INSTANCE;UiKit.text(g,"COMFORT VOICE PROCESSING • OPUS 48 kHz / 20 ms",30,135,t.accent());int y=152;String[] names={"Microphone Gain","Noise Gate","Suppression Strength","Activation Threshold","VAD Hangover","AGC Target","AGC Max Gain","Compressor Strength","Voice Clarity","Opus Bitrate"};for(int i=0;i<names.length;i++){setting(g,t,30,y,620,names[i],switch(i){case 0->"Manual pre-DSP input gain";case 1->"Base threshold before adaptive noise-floor tracking";case 2->"How strongly idle noise is attenuated";case 3->"VAD opens above this level";case 4->"Keeps word endings from being clipped";case 5->"Target speech loudness";case 6->"Maximum automatic boost";case 7->"Smooth loud syllables before limiter";case 8->"Gentle presence enhancement";default->"Opus VOIP bitrate; 32 kbps is the balanced default";});UiKit.slider(g,new UiKit.Rect(345,y+15,210,14),audioValue(i,c),i==3?t.amber():i==7?t.purple():t.green(),t);value(g,t,565,y+9,70,26,audioLabel(i,c));y+=36;}
        UiKit.text(g,"PROCESSING MODULES",680,135,t.accent());UiKit.panel(g,675,152,285,122,t.panel(),t.border());UiKit.text(g,"Automatic Gain",692,174,t.text());UiKit.toggle(g,new UiKit.Rect(875,165,62,25),c.agcEnabled,t);UiKit.text(g,"Speech Compressor",692,210,t.text());UiKit.toggle(g,new UiKit.Rect(875,201,62,25),c.compressorEnabled,t);UiKit.text(g,"Opus FEC",692,246,t.text());UiKit.toggle(g,new UiKit.Rect(875,237,62,25),c.fecEnabled,t);
        UiKit.text(g,"LIVE DIAGNOSTICS",680,302,t.accent());UiKit.panel(g,675,319,285,177,t.panel(),t.border());var d=ClientDiagnostics.INSTANCE;var st=ClientVoiceController.get().audioStats();line(g,t,692,340,"Mic",String.format("%.1f dB",ClientVoiceController.get().micLevelDb()),t.green());line(g,t,692,364,"Noise floor",String.format("%.1f dB",st.noiseFloorDb()),t.muted());line(g,t,692,388,"AGC",String.format("+%.1f dB",st.agcGainDb()),t.green());line(g,t,692,412,"Queue",ClientVoiceController.get().sendQueue()+" / 12",t.accent());line(g,t,692,436,"Sent / recv",d.sentFrames.get()+" / "+d.receivedFrames.get(),t.text());line(g,t,692,460,"FEC / PLC",d.fecFrames.get()+" / "+d.plcFrames.get(),t.purple());}
    private void keybinds(GuiGraphics g,UiTheme t){UiKit.text(g,"VOICE KEYBINDS",30,135,t.accent());String[][] rows={{"Proximity Push-to-Talk",KeyBindings.PTT.getTranslatedKeyMessage().getString()},{"Group Push-to-Talk",KeyBindings.GROUP_PTT.getTranslatedKeyMessage().getString()},{"Mute Self",KeyBindings.MUTE.getTranslatedKeyMessage().getString()},{"Deafen",KeyBindings.DEAFEN.getTranslatedKeyMessage().getString()},{"Open Settings",KeyBindings.SETTINGS.getTranslatedKeyMessage().getString()},{"Open Groups",KeyBindings.GROUPS.getTranslatedKeyMessage().getString()},{"Open Player Mixer",KeyBindings.MIXER.getTranslatedKeyMessage().getString()}};int y=160;for(String[] r:rows){UiKit.panel(g,60,y,880,44,t.panel(),t.border());UiKit.text(g,r[0],82,y+16,t.text());value(g,t,725,y+8,190,28,r[1]);y+=52;}UiKit.text(g,"Rebind these normally from Minecraft Controls. V + G simultaneously transmits to both channels without duplicate client encoding.",60,530,t.muted());}
    private void themes(GuiGraphics g,UiTheme t){UiKit.text(g,"THEME LIBRARY",30,135,t.accent());String[] themes={"Deep Slate","Amethyst","Frost","Crimson"};for(int i=0;i<themes.length;i++){int x=40+(i%2)*465,y=160+(i/2)*120;boolean on=ClientConfig.INSTANCE.theme.equals(themes[i]);UiKit.panel(g,x,y,440,98,t.panel(),on?t.accent():t.border());UiKit.text(g,themes[i],x+20,y+18,on?t.accent():t.text());g.fill(x+20,y+48,x+105,y+65,i==1?0xFFB56CFF:i==2?0xFF41D8FF:i==3?0xFFFF5F76:0xFF20D6D2);g.fill(x+120,y+48,x+205,y+65,t.green());g.fill(x+220,y+48,x+305,y+65,t.purple());UiKit.text(g,on?"ACTIVE":"Click to apply",x+20,y+76,on?t.green():t.muted());}UiKit.text(g,"STUDIO APPEARANCE",30,420,t.accent());UiKit.panel(g,40,440,900,62,t.panel(),t.border());UiKit.text(g,"UI Opacity",60,464,t.text());UiKit.slider(g,new UiKit.Rect(145,458,170,14),(ClientConfig.INSTANCE.uiOpacity-.5f)/.5f,t.accent(),t);UiKit.text(g,"UI Scale",350,464,t.text());UiKit.slider(g,new UiKit.Rect(420,458,170,14),(ClientConfig.INSTANCE.uiScale-.75f)/.55f,t.purple(),t);UiKit.text(g,"Rounded",625,464,t.text());UiKit.toggle(g,new UiKit.Rect(700,452,62,25),ClientConfig.INSTANCE.rounded,t);}
    private void advanced(GuiGraphics g,UiTheme t){ClientConfig c=ClientConfig.INSTANCE;UiKit.text(g,"COMFORT PROFILES",30,135,t.accent());String[] p={"NATURAL","CLEAR","COMPETITIVE","NOISY ROOM","BROADCAST"};for(int i=0;i<p.length;i++)UiKit.button(g,new UiKit.Rect(40+i*184,158,170,34),p[i],false,new UiKit.Rect(40+i*184,158,170,34).hit(mx,my),t);UiKit.text(g,"SESSION & NETWORK",30,220,t.accent());UiKit.panel(g,40,238,920,210,t.panel(),t.border());UiKit.text(g,"Streamer Mode",62,263,t.text());UiKit.toggle(g,new UiKit.Rect(250,254,65,26),c.streamerMode,t);UiKit.text(g,"VAD target",62,305,t.text());value(g,t,215,296,150,28,c.vadTargetsGroup?"GROUP":"PROXIMITY");UiKit.text(g,"Jitter cushion",62,347,t.text());UiKit.slider(g,new UiKit.Rect(215,342,150,14),(c.jitterFrames-1f)/5f,t.purple(),t);UiKit.text(g,c.jitterFrames*20+" ms",380,347,t.text());var pol=ClientVoiceController.get().policy();line(g,t,520,263,"Server Voice",pol.voiceEnabled()?"READY":"DISABLED",pol.voiceEnabled()?t.green():t.red());line(g,t,520,305,"Group Voice",pol.groupsEnabled()?"READY":"DISABLED",pol.groupsEnabled()?t.purple():t.red());line(g,t,520,347,"Max Group",Integer.toString(pol.maxGroupSize()),t.text());line(g,t,520,389,"Input",ClientVoiceController.get().micError().isBlank()?"READY":"ERROR",ClientVoiceController.get().micError().isBlank()?t.green():t.red());line(g,t,520,423,"Output",ClientVoiceController.get().outputError().isBlank()?"READY":"ERROR",ClientVoiceController.get().outputError().isBlank()?t.green():t.red());UiKit.button(g,new UiKit.Rect(40,470,280,32),"OPEN GROUPS",false,new UiKit.Rect(40,470,280,32).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(345,470,280,32),"OPEN PLAYER MIXER",false,new UiKit.Rect(345,470,280,32).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(650,470,310,32),"RESET DIAGNOSTICS",false,new UiKit.Rect(650,470,310,32).hit(mx,my),t);}
    private void bottom(GuiGraphics g,UiTheme t){UiKit.button(g,new UiKit.Rect(28,516,130,28),"BACK",false,new UiKit.Rect(28,516,130,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(390,516,170,28),"RESET DEFAULTS",false,new UiKit.Rect(390,516,170,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(570,516,150,28),"APPLY",false,new UiKit.Rect(570,516,150,28).hit(mx,my),t);UiKit.button(g,new UiKit.Rect(730,516,242,28),"SAVE & CLOSE",true,new UiKit.Rect(730,516,242,28).hit(mx,my),t);}
    @Override public boolean mouseClicked(double x,double y,int b){transform(x,y);if(b!=0)return super.mouseClicked(x,y,b);for(int i=0;i<TABS.length;i++){int tx=28+i*136;if(new UiKit.Rect(tx,84,128,34).hit(mx,my)){if(i==2){Minecraft.getInstance().setScreen(new OverlayEditorScreen(this));return true;}if(i==3){Minecraft.getInstance().setScreen(new GroupScreen(this));return true;}page=i;return true;}}if(new UiKit.Rect(28,516,130,28).hit(mx,my)){onClose();return true;}if(new UiKit.Rect(390,516,170,28).hit(mx,my)){ClientConfig.INSTANCE.reset();return true;}if(new UiKit.Rect(570,516,150,28).hit(mx,my)){ClientConfig.INSTANCE.save();return true;}if(new UiKit.Rect(730,516,242,28).hit(mx,my)){ClientConfig.INSTANCE.save();onClose();return true;}if(page==0)return clickGeneral();if(page==1)return clickAudio();if(page==5)return clickThemes();if(page==6)return clickAdvanced();return true;}
    private boolean clickGeneral(){ClientConfig c=ClientConfig.INSTANCE;if(hit(345,167,210,18)){drag=0;updateDrag();return true;}if(hit(345,215,210,18)){drag=1;updateDrag();return true;}if(hit(405,257,230,28)){c.activationMode=c.activationMode==ClientConfig.ActivationMode.PUSH_TO_TALK?ClientConfig.ActivationMode.VOICE_ACTIVATION:ClientConfig.ActivationMode.PUSH_TO_TALK;return true;}if(hit(570,306,65,26)){c.suppressionStrength=c.suppressionStrength>.05f?0f:.78f;return true;}if(hit(570,354,65,26)){c.spatialVoice=!c.spatialVoice;return true;}if(hit(345,407,210,18)){drag=2;updateDrag();return true;}if(hit(330,449,305,28)){cycleInput();return true;}if(hit(330,497,305,28)){cycleOutput();return true;}if(hit(692,458,118,28)){Minecraft.getInstance().setScreen(new GroupScreen(this));return true;}if(hit(820,458,118,28)){Minecraft.getInstance().setScreen(new PlayerMixerScreen(this));return true;}return true;}
    private boolean clickAudio(){int y=167;for(int i=0;i<10;i++,y+=36)if(hit(345,y,210,18)){drag=10+i;updateDrag();return true;}if(hit(875,165,62,25)){ClientConfig.INSTANCE.agcEnabled=!ClientConfig.INSTANCE.agcEnabled;return true;}if(hit(875,201,62,25)){ClientConfig.INSTANCE.compressorEnabled=!ClientConfig.INSTANCE.compressorEnabled;return true;}if(hit(875,237,62,25)){ClientConfig.INSTANCE.fecEnabled=!ClientConfig.INSTANCE.fecEnabled;return true;}return true;}
    private boolean clickThemes(){String[] themes={"Deep Slate","Amethyst","Frost","Crimson"};for(int i=0;i<themes.length;i++){int x=40+(i%2)*465,y=160+(i/2)*120;if(hit(x,y,440,98)){ClientConfig.INSTANCE.theme=themes[i];return true;}}if(hit(145,458,170,18)){drag=30;updateDrag();return true;}if(hit(420,458,170,18)){drag=31;updateDrag();return true;}if(hit(700,452,62,25)){ClientConfig.INSTANCE.rounded=!ClientConfig.INSTANCE.rounded;return true;}return true;}
    private boolean clickAdvanced(){for(int i=0;i<5;i++)if(hit(40+i*184,158,170,34)){profile(i);return true;}if(hit(250,254,65,26)){ClientConfig.INSTANCE.streamerMode=!ClientConfig.INSTANCE.streamerMode;return true;}if(hit(215,296,150,28)){ClientConfig.INSTANCE.vadTargetsGroup=!ClientConfig.INSTANCE.vadTargetsGroup;return true;}if(hit(215,342,150,18)){drag=40;updateDrag();return true;}if(hit(40,470,280,32)){Minecraft.getInstance().setScreen(new GroupScreen(this));return true;}if(hit(345,470,280,32)){Minecraft.getInstance().setScreen(new PlayerMixerScreen(this));return true;}if(hit(650,470,310,32)){ClientDiagnostics.INSTANCE.reset();return true;}return true;}
    @Override public boolean mouseDragged(double x,double y,int b,double dx,double dy){transform(x,y);if(b==0&&drag>=0){updateDrag();return true;}return super.mouseDragged(x,y,b,dx,dy);}@Override public boolean mouseReleased(double x,double y,int b){drag=-1;return super.mouseReleased(x,y,b);}private void updateDrag(){ClientConfig c=ClientConfig.INSTANCE;float v;switch(drag){case 0->c.masterVolume=2*slider(mx,345,210);case 1->c.groupVolume=2*slider(mx,345,210);case 2->c.proximityRange=4+60*slider(mx,345,210);case 10->c.microphoneGainDb=-12+36*slider(mx,345,210);case 11->c.noiseGateDb=-80+60*slider(mx,345,210);case 12->c.suppressionStrength=slider(mx,345,210);case 13->c.activationThresholdDb=-65+50*slider(mx,345,210);case 14->c.vadHangoverMs=Math.round(600*slider(mx,345,210)/20)*20;case 15->c.agcTargetDb=-30+22*slider(mx,345,210);case 16->c.agcMaxGainDb=24*slider(mx,345,210);case 17->c.compressorStrength=slider(mx,345,210);case 18->c.voiceClarity=slider(mx,345,210);case 19->c.opusBitrateKbps=Math.round(16+48*slider(mx,345,210));case 30->c.uiOpacity=.5f+.5f*slider(mx,145,170);case 31->c.uiScale=.75f+.55f*slider(mx,420,170);case 40->c.jitterFrames=Math.max(1,Math.min(6,Math.round(1+5*slider(mx,215,150))));default->{}}}
    private float audioValue(int i,ClientConfig c){return switch(i){case 0->(c.microphoneGainDb+12)/36f;case 1->(c.noiseGateDb+80)/60f;case 2->c.suppressionStrength;case 3->(c.activationThresholdDb+65)/50f;case 4->c.vadHangoverMs/600f;case 5->(c.agcTargetDb+30)/22f;case 6->c.agcMaxGainDb/24f;case 7->c.compressorStrength;case 8->c.voiceClarity;default->(c.opusBitrateKbps-16)/48f;};}private String audioLabel(int i,ClientConfig c){return switch(i){case 0->String.format("%+.1f dB",c.microphoneGainDb);case 1->String.format("%.0f dB",c.noiseGateDb);case 2->Math.round(c.suppressionStrength*100)+"%";case 3->String.format("%.0f dB",c.activationThresholdDb);case 4->c.vadHangoverMs+" ms";case 5->String.format("%.0f dB",c.agcTargetDb);case 6->Math.round(c.agcMaxGainDb)+" dB";case 7->Math.round(c.compressorStrength*100)+"%";case 8->Math.round(c.voiceClarity*100)+"%";default->c.opusBitrateKbps+" kbps";};}
    private void profile(int id){ClientConfig c=ClientConfig.INSTANCE;switch(id){case 0->{c.suppressionStrength=.55f;c.agcTargetDb=-19;c.agcMaxGainDb=10;c.compressorStrength=.45f;c.voiceClarity=.18f;c.opusBitrateKbps=32;c.jitterFrames=3;}case 1->{c.suppressionStrength=.68f;c.agcTargetDb=-18;c.agcMaxGainDb=12;c.compressorStrength=.58f;c.voiceClarity=.36f;c.opusBitrateKbps=36;c.jitterFrames=2;}case 2->{c.suppressionStrength=.62f;c.agcTargetDb=-17;c.agcMaxGainDb=8;c.compressorStrength=.52f;c.voiceClarity=.48f;c.opusBitrateKbps=28;c.jitterFrames=1;}case 3->{c.suppressionStrength=.92f;c.noiseGateDb=-46;c.agcTargetDb=-18;c.agcMaxGainDb=8;c.compressorStrength=.72f;c.voiceClarity=.24f;c.opusBitrateKbps=32;c.jitterFrames=3;}default->{c.suppressionStrength=.72f;c.agcTargetDb=-16;c.agcMaxGainDb=10;c.compressorStrength=.82f;c.voiceClarity=.34f;c.opusBitrateKbps=48;c.jitterFrames=3;}}}
    private void cycleInput(){ClientConfig c=ClientConfig.INSTANCE;List<String> d=AudioDevices.inputs();int i=d.indexOf(c.inputDevice);c.inputDevice=d.get((i+1+d.size())%d.size());ClientVoiceController.get().restartInput();}private void cycleOutput(){ClientConfig c=ClientConfig.INSTANCE;List<String>d=AudioDevices.outputs();int i=d.indexOf(c.outputDevice);c.outputDevice=d.get((i+1+d.size())%d.size());ClientVoiceController.get().restartOutput();}
    private void setting(GuiGraphics g,UiTheme t,int x,int y,int w,String title,String desc){UiKit.panel(g,x,y,w,42,t.panel(),t.border());UiKit.text(g,title,x+15,y+9,t.text());UiKit.text(g,desc,x+15,y+24,t.muted());}private void value(GuiGraphics g,UiTheme t,int x,int y,int w,int h,String s){UiKit.panel(g,x,y,w,h,t.panel2(),t.border());UiKit.centered(g,s,x+w/2,y+(h-8)/2,t.text());}private void line(GuiGraphics g,UiTheme t,int x,int y,String k,String v,int color){UiKit.text(g,k,x,y,t.muted());UiKit.text(g,v,x+130,y,color);}private boolean hit(int x,int y,int w,int h){return new UiKit.Rect(x,y,w,h).hit(mx,my);}private static float slider(double x,int sx,int w){return Math.max(0,Math.min(1,(float)((x-sx)/w)));}
    @Override public void onClose(){ClientConfig.INSTANCE.save();Minecraft.getInstance().setScreen(parent);}private void transform(double x,double y){scale=Math.max(.25f,Math.min((width-8f)/VW,(height-8f)/VH));ox=(width-VW*scale)/2;oy=(height-VH*scale)/2;mx=(x-ox)/scale;my=(y-oy)/scale;}
}
