org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.10

mod_id=motifx
mod_name=MotifX
mod_version=0.2.0-dev.1
mod_group_id=dev.harekuto.motifx
mod_authors=Harekuto
mod_description=Composable motion runtime, animation graph, compatibility SPI, diagnostics and developer tooling for Minecraft mods.
